### ISSUE TITLE
Server behind a reverse proxy has wrong Service Url

### ISSUE THREAD

**Issue by mikegleasonjr** [codeproject/CodeProject.AI-Server#103] opened 2024-04-12 02:25 UTC
**Area of Concern**
- [x] Server
- [ ] Behaviour of one or more Modules [provide name(s), e.g. ObjectDetectionYolo]
- [ ] Installer
- [ ] Runtime [e.g. Python3.7, .NET]
- [ ] Module packages [e.g. PyTorch)
- [ ] Something else

**Describe the bug**

Hosting codeproject ai server through docker, runs fine by itself. Putting a reverse proxy in front makes the Service Url to be wrong.

- host: http://codeprojectai.home.lan/
- service url detected: http://codeprojectai.home.lan:32168

If I edit quickly the Service Url to remove the port, the UIO connects to the backend properly.

**Expected behavior**

service url to be: http://codeprojectai.home.lan

**Screenshots**

![image](https://github.com/codeproject/CodeProject.AI-Server/assets/1644534/11dfa449-982a-49f2-a328-43bdcf1413d5)

![image](https://github.com/codeproject/CodeProject.AI-Server/assets/1644534/410f9c2e-d533-4d52-b67a-19898ebb92a4)

**Your System (please complete the following information):**

- CodeProject.AI Server version: codeproject/ai-server:2.6.2

**Additional context**

Thanks

**Comment by ninjamonkey198206** [comment] 2024-04-12 23:48
I have had the same issue for some time, except that the connection fails again 10-20 sec after removing the port.

**Comment by arychj** [comment] 2024-04-15 19:42
The issue is [here](https://github.com/codeproject/CodeProject.AI-Server/blob/ac1a881e10714e13d566aa35f9e976d403f4b319/src/server/wwwroot/assets/server.js#L16). `window.location.port` will only return a value if running on a non-default port (aka not 80 or 443).

Looks like @miguelangel-nubla already has a [PR](https://github.com/codeproject/CodeProject.AI-Server/pull/102) open for it.

**Comment by ChrisMaunder** [comment] 2024-04-18 17:55
Fixed in next release

**Closed by ChrisMaunder** 2024-04-18 17:55 UTC
